"""empty message

Revision ID: 37202f3807eb
Revises: a1ba4c53cadc
Create Date: 2020-09-28 00:53:20.762949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37202f3807eb'
down_revision = 'a1ba4c53cadc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('groupme_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('groupme_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group')
    # ### end Alembic commands ###
