"""empty message

Revision ID: 373480932842
Revises: c50b93c19498
Create Date: 2021-01-10 22:18:56.880479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '373480932842'
down_revision = 'c50b93c19498'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plugin', sa.Column('help', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plugin', 'help')
    # ### end Alembic commands ###
