"""empty message

Revision ID: c51f0b3bc185
Revises: 
Create Date: 2019-09-10 00:21:38.044636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c51f0b3bc185'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('groupme_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(500)),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('groupme_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
